### PR TITLE
Grunt and Bower migration

### PR DESCRIPTION
**Pull request by moodmosaic**
These are the minimum changes required to migrate (if necessary) the project to [Grunt](http://gruntjs.com/) and [Bower](http://bower.io/).

The end result is a composable, customizable, continuous, task automation pipeline; decoupled from text editors and IDEs.
### Installation

The proposed changes require only two npm modules to be installed as global packages:

```
# The first required npm module is Bower:
npm install -g bower

# The second required npm module is Grunt's command line interface:
npm install -g grunt-cli
```

After installing the above npm modules as global packages execute:

```
git clean -d -x -f | npm cache clean && npm install && bower install
```
### Usage

For previewing while programming execute `grunt serve`. To run a build execute `grunt`.
### How it works

Task automation is performed by Grunt. Package management is performed by Bower. (The difference between npm and Bower is described [here](http://stackoverflow.com/a/18652918/467754).)

Grunt processes the task automation pipeline defined in the [Gruntfile](http://gruntjs.com/getting-started#the-gruntfile). The proposed Gruntfile is composed by [generator-angular](https://github.com/yeoman/generator-angular), as well as this [post](http://newtriks.com/2013/11/29/environment-specific-configuration-in-angularjs-using-grunt/), and this [post](http://nikosbaxevanis.com/blog/2014/04/03/typescript-slash-grunt-slash-angular/).
### Task automations

_The complete list of tasks is defined in the Gruntfile._

During programming:
- LiveReload
- JSHint
- Karma
- (Optional) TypeScript compilation

When running a build:
- JSHint
- Karma
- (Optional) TypeScript compilation<sup>1</sup>
- (Optional) Environment Specific Configuration<sup>2</sup>
- Convertion from local URLs to CDN ones
- Vendor-prefixed CSS properties
- Minification
- Bundling

---
###### <sup>1</sup>TypeScript auto-compilation

To enable TypeScript auto-compilation in the task automation pipeline, first install TypeScript globally:

```
npm install -g typescript
```

Then, rename a _.js_ file to _.ts_ (e.g. app.js → app.ts) and reference the Angular declaration source file:

```
/// <reference path='../bower_components/DefinitelyTyped/angularjs/angular.d.ts' />
```
###### <sup>2</sup>Environment Specific Configuration

Injecting environment specific constant values (e.g. server URLs, etc) is supported as described in this [post](http://newtriks.com/2013/11/29/environment-specific-configuration-in-angularjs-using-grunt/). The first part (up to _"Loading the config with the app"_) has been already setup in the Gruntfile.

### CODE REVIEW

**Comment by ploeh** [comment]
Thank you. I took a look at this, installed everything, and it _does_ run... What does it do?

Basically, what I can see that it does right now is that it adds thousands of files to my system, but I don't understand what benefit I gain from it...

**Comment by moodmosaic** [comment]
> it adds thousands of files to my system

It adds npm packages under the local _node_modules_ folder and bower components under the _app/bower_components_ folder – it doesn't affect anything outside the git's repository folder.

> What does it do / what benefit I gain from it

You can imagine a .NET _build-release_ script but for _angular-seed_-based applications where some parts of the script are available on-the-fly, during programming. (e.g. LiveReload, Linting, Karma, etc.)

It makes it easier to work with _angular-seed_-based applications by enabling _most_ of the [Yeoman](http://yeoman.io/) workflow without modifying existing application code, and without having to install anything globally.

---

You can run the project (to edit some HTML/CSS or JavaScript) and fiddle with it via

```
$ grunt serve
```

For something similar to a .NET _build-release_ script, you may try

```
$ grunt
```

**Comment by ploeh** [comment]
...but, this project doesn't need anything like that...

If I want to run the server, I just go

```
scripts/web-server.js
```

and if I want to verify if it's OK, I just run

```
scripts/test.sh
```

Typically, I keep both of them running together with the `&` bash switch.

Why do I need all that extra stuff?

**Comment by moodmosaic** [comment]
In the description I wrote _(if necessary)_:

> These are the minimum changes required to migrate (if necessary) the project to Grunt and Bower.

You don't necessarily need it (please, feel free to close this anytime).

---

I _do_ wanted to show it to you though, in case you find it useful for large codebases, because it is quite composable and customizable.

**Comment by ploeh** [comment]
And I _am_ curious, but the problem is that I don't (yet) understand why I'd need Grunt and Bower. Part of the problem is that I don't really know what Grunt and Bower do.

**Comment by moodmosaic** [comment]
Bower is a package manager, quite similar to NuGet – most of the advantages of NuGet apply to Bower.

Grunt is quite similar to MSBuild:
- It has a command line tool [grunt-cli](https://github.com/gruntjs/grunt-cli) like _msbuild.exe_.
- It reads a _Gruntfile.js_ which is essentially a task pipeline similar to *.msbuild files.

In .NET, this pull request would add NuGet support, a _build-release.sh_ script and an *.msbuild file.

**Comment by moodmosaic** [comment]
The equivalent of a _build-release.sh_ script here is

```
$ grunt
```
- It cleans any previous build runs.
- It adds vendor-prefixed CSS properties.
- It runs all the unit tests.
- It verifies that all required Bower components are referenced in index.html.
- It obfuscates JavaScript and CSS files.
- It minifies JavaScript and CSS files.
- It compresses images.
- It produces a `/dist` folder with all the above which is the _Release_ build of the application.

**Comment by moodmosaic** [comment]
Another benefit that this build system provides is environment specific configuration, although in this particular pull request it's not enabled.

Right now the UI assumes that the Web API (backend) is on the same path. Assuming that CORS is enabled, you could automatically set a deployment-specific backend URL when running a _Release_ build.

**Comment by moodmosaic** [comment]
All these aren't really necessary for a demo UI. This kind of build automation though is interesting, I think.

**Comment by moodmosaic** [comment]
Closing this Pull Request as [it's now possible to do all that from inside Visual Studio](http://www.hanselman.com/blog/IntroducingGulpGruntBowerAndNpmSupportForVisualStudio.aspx) if needed.

**Pull request closed without merging**
